mdapi/objects/Task_Removal_Setting__mdt.object
<CustomObject>
    <description>Houses a setting for Tasks that determines the cutoff point for deleting old, completed Tasks via a Batch Apex operation.</description>
    <fields>
        <fullName>Cutoff_Days__c</fullName>
        <description>The number of days before today that identifies the cutoff point for Batch Apex Task Removal.  (Example: A value of 120 means that completed Tasks that are 120 days old will be deleted on the next Batch Apex Task Removal operation)</description>
        <inlineHelpText>The number of days before today that identifies the cutoff point for Batch Apex Task Removal.  (Example: A value of 120 means that completed Tasks that are 120 days old will be deleted on the next Batch Apex Task Removal operation)</inlineHelpText>
        <label>Cutoff Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Task Removal Setting</label>
    <pluralLabel>Task Removal Settings</pluralLabel>
</CustomObject>

mdapi/classes/BatchTaskRemoval.cls
global class BatchTaskRemoval implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        Decimal decimalDays = [SELECT Cutoff_Days__c FROM Task_Removal_Setting__mdt][0].Cutoff_Days__c;
        
        Integer days = Integer.valueOf(decimalDays);
        
        Date cutoffDateUnformatted = System.today().addDays(-days);
        
        String cutOffDate = String.valueOf(cutoffDateUnformatted);
        
        return Database.getQueryLocator('SELECT Id FROM Task WHERE IsClosed = true AND Completed_Date__c <= ' + cutoffDate);
    }
    
    global void execute(Database.BatchableContext bc, List<Task> scope) {
        
        delete scope;
    }
    
    global void finish(Database.BatchableContext bc) {
        
        
    }
}